--------------------------------------------------------
-- Archivo creado  - jueves-julio-25-2024   
--------------------------------------------------------
DROP SEQUENCE "DBADMIN"."SECUENCIA_PEDIDO";
DROP SEQUENCE "DBADMIN"."SEQ_DEVOLUCION";
DROP SEQUENCE "DBADMIN"."SEQ_ID_SUCURSAL";
DROP TABLE "DBADMIN"."ACCESORIO" cascade constraints;
DROP TABLE "DBADMIN"."CATEGORIA" cascade constraints;
DROP TABLE "DBADMIN"."CLIENTE" cascade constraints;
DROP TABLE "DBADMIN"."DETALLE_PEDIDO" cascade constraints;
DROP TABLE "DBADMIN"."DEVOLUCION" cascade constraints;
DROP TABLE "DBADMIN"."EMPLEADO" cascade constraints;
DROP TABLE "DBADMIN"."PEDIDO" cascade constraints;
DROP TABLE "DBADMIN"."PRODUCTO" cascade constraints;
DROP TABLE "DBADMIN"."ROL" cascade constraints;
DROP TABLE "DBADMIN"."SUCURSAL" cascade constraints;
DROP TABLE "DBADMIN"."USUARIO" cascade constraints;
DROP TABLE "DBADMIN"."VENTA" cascade constraints;
DROP VIEW "DBADMIN"."VISTAACCESORIOS";
DROP VIEW "DBADMIN"."VISTACATEGORIAS";
DROP VIEW "DBADMIN"."VISTACLIENTES";
DROP VIEW "DBADMIN"."VISTADETALLESDEDIDO";
DROP VIEW "DBADMIN"."VISTADEVOLUCIONES";
DROP VIEW "DBADMIN"."VISTAEMPLEADOS";
DROP VIEW "DBADMIN"."VISTAPEDIDOS";
DROP VIEW "DBADMIN"."VISTAPRODUCTOS";
DROP VIEW "DBADMIN"."VISTAROLES";
DROP VIEW "DBADMIN"."VISTASUCURSALES";
DROP VIEW "DBADMIN"."VISTAUSUARIOS";
DROP VIEW "DBADMIN"."VISTAVENTAS";
DROP PROCEDURE "DBADMIN"."CONSULTARACCESORIOS";
DROP PROCEDURE "DBADMIN"."CONSULTARCATEGORIA";
DROP PROCEDURE "DBADMIN"."CONSULTARDETALLEPEDIDO";
DROP PROCEDURE "DBADMIN"."CONSULTARDEVOLUCIONES";
DROP PROCEDURE "DBADMIN"."CONSULTARPEDIDOS";
DROP PROCEDURE "DBADMIN"."CONSULTARPRODUCTOS";
DROP PROCEDURE "DBADMIN"."CONSULTARROL";
DROP PROCEDURE "DBADMIN"."CONSULTARSUCURSAL";
DROP PROCEDURE "DBADMIN"."CONSULTARUSUARIOPORUSERNAME";
DROP PROCEDURE "DBADMIN"."CONSULTARUSUARIOS";
DROP PROCEDURE "DBADMIN"."CONSULTARVENTA";
DROP PROCEDURE "DBADMIN"."DESACTIVARUSUARIO";
DROP PROCEDURE "DBADMIN"."ELIMINARACCESORIO";
DROP PROCEDURE "DBADMIN"."ELIMINARCATEGORIA";
DROP PROCEDURE "DBADMIN"."ELIMINARDETALLEPEDIDO";
DROP PROCEDURE "DBADMIN"."ELIMINARDEVOLUCIONES";
DROP PROCEDURE "DBADMIN"."ELIMINARPEDIDOS";
DROP PROCEDURE "DBADMIN"."ELIMINARPRODUCTO";
DROP PROCEDURE "DBADMIN"."ELIMINARROL";
DROP PROCEDURE "DBADMIN"."ELIMINARSUCURSAL";
DROP PROCEDURE "DBADMIN"."ELIMINARUSUARIO";
DROP PROCEDURE "DBADMIN"."ELIMINARVENTA";
DROP PROCEDURE "DBADMIN"."MODIFICARACCESORIO";
DROP PROCEDURE "DBADMIN"."MODIFICARCATEGORIA";
DROP PROCEDURE "DBADMIN"."MODIFICARDETALLEPEDIDO";
DROP PROCEDURE "DBADMIN"."MODIFICARDEVOLUCION";
DROP PROCEDURE "DBADMIN"."MODIFICARPEDIDO";
DROP PROCEDURE "DBADMIN"."MODIFICARPRODUCTO";
DROP PROCEDURE "DBADMIN"."MODIFICARROL";
DROP PROCEDURE "DBADMIN"."MODIFICARSUCURSAL";
DROP PROCEDURE "DBADMIN"."MODIFICARUSUARIO";
DROP PROCEDURE "DBADMIN"."MODIFICARVENTA";
DROP PROCEDURE "DBADMIN"."REGISTRARACCESORIO";
DROP PROCEDURE "DBADMIN"."REGISTRARCATEGORIA";
DROP PROCEDURE "DBADMIN"."REGISTRARDETALLEPEDIDO";
DROP PROCEDURE "DBADMIN"."REGISTRARDEVOLUCION";
DROP PROCEDURE "DBADMIN"."REGISTRARPEDIDO";
DROP PROCEDURE "DBADMIN"."REGISTRARPRODUCTO";
DROP PROCEDURE "DBADMIN"."REGISTRARROL";
DROP PROCEDURE "DBADMIN"."REGISTRARSUCURSAL";
DROP PROCEDURE "DBADMIN"."REGISTRARUSUARIO";
DROP PROCEDURE "DBADMIN"."REGISTRARVENTA";
--------------------------------------------------------
--  DDL for Sequence SECUENCIA_PEDIDO
--------------------------------------------------------

   CREATE SEQUENCE  "DBADMIN"."SECUENCIA_PEDIDO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DEVOLUCION
--------------------------------------------------------

   CREATE SEQUENCE  "DBADMIN"."SEQ_DEVOLUCION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ID_SUCURSAL
--------------------------------------------------------

   CREATE SEQUENCE  "DBADMIN"."SEQ_ID_SUCURSAL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ACCESORIO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."ACCESORIO" 
   (	"ID_ACCESORIO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER, 
	"ID_CATEGORIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_PEDIDO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."DETALLE_PEDIDO" 
   (	"ID_DETALLE" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_PEDIDO" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEVOLUCION
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."DEVOLUCION" 
   (	"ID_DEVOLUCION" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"FECHA_DEVOLUCION" DATE, 
	"CANTIDAD" NUMBER, 
	"MOTIVO" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"ID_SUCURSAL" NUMBER, 
	"ACTIVO" NUMBER(1,0), 
	"ID_USUARIO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."PEDIDO" 
   (	"ID_PEDIDO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CLIENTE" NUMBER, 
	"FECHA_PEDIDO" TIMESTAMP (6), 
	"ESTADO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER, 
	"RUTA_IMAGEN" VARCHAR2(1024 BYTE), 
	"ID_CATEGORIA" NUMBER, 
	"ID_SUCURSAL" NUMBER, 
	"ACTIVO" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."ROL" 
   (	"ID_ROL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."SUCURSAL" 
   (	"ID_SUCURSAL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."USUARIO" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(512 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"CORREO" VARCHAR2(25 BYTE), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"ID_USUARIO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ROL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."VENTA" 
   (	"ID_VENTA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBTOTAL" NUMBER(10,2), 
	"IVA" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View VISTAACCESORIOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAACCESORIOS" ("ID_ACCESORIO", "NOMBRE", "DESCRIPCION", "PRECIO", "STOCK", "ID_CATEGORIA") AS 
  SELECT ID_ACCESORIO, NOMBRE, DESCRIPCION, PRECIO, STOCK, ID_CATEGORIA
FROM Accesorio
;
--------------------------------------------------------
--  DDL for View VISTACATEGORIAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTACATEGORIAS" ("ID_CATEGORIA", "NOMBRE", "ACTIVO", "DESCRIPCION") AS 
  SELECT ID_CATEGORIA, NOMBRE, ACTIVO, DESCRIPCION
FROM categoria
;
--------------------------------------------------------
--  DDL for View VISTACLIENTES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTACLIENTES" ("ID_CLIENTE", "NOMBRE", "APELLIDO", "TELEFONO", "CORREO", "DIRECCION", "USERNAME", "PASSWORD", "ACTIVO") AS 
  SELECT ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, USERNAME, PASSWORD, ACTIVO
FROM cliente
;
--------------------------------------------------------
--  DDL for View VISTADETALLESDEDIDO
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTADETALLESDEDIDO" ("ID_DETALLE", "ID_PEDIDO", "ID_PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL") AS 
  SELECT ID_DETALLE, ID_PEDIDO, ID_PRODUCTO, CANTIDAD, PRECIO, TOTAL
FROM detalle_pedido
;
--------------------------------------------------------
--  DDL for View VISTADEVOLUCIONES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTADEVOLUCIONES" ("ID_DEVOLUCION", "ID_CLIENTE", "ID_PRODUCTO", "FECHA_DEVOLUCION", "CANTIDAD", "MOTIVO") AS 
  SELECT ID_DEVOLUCION, ID_CLIENTE, ID_PRODUCTO, FECHA_DEVOLUCION, CANTIDAD, MOTIVO
FROM devolucion
;
--------------------------------------------------------
--  DDL for View VISTAEMPLEADOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAEMPLEADOS" ("ID_EMPLEADO", "USERNAME", "NOMBRE", "PASSWORD", "APELLIDO", "CORREO", "TELEFONO", "ID_SUCURSAL", "ACTIVO") AS 
  SELECT ID_EMPLEADO, USERNAME, NOMBRE, PASSWORD, APELLIDO, CORREO, TELEFONO, ID_SUCURSAL, ACTIVO
FROM empleado
;
--------------------------------------------------------
--  DDL for View VISTAPEDIDOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAPEDIDOS" ("ID_PEDIDO", "ID_CLIENTE", "FECHA_PEDIDO", "ESTADO") AS 
  SELECT ID_PEDIDO, ID_CLIENTE, FECHA_PEDIDO, ESTADO
FROM pedido
;
--------------------------------------------------------
--  DDL for View VISTAPRODUCTOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAPRODUCTOS" ("ID_PRODUCTO", "DESCRIPCION", "PRECIO", "STOCK", "ID_CATEGORIA", "ID_SUCURSAL", "ACTIVO") AS 
  SELECT ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK, ID_CATEGORIA, ID_SUCURSAL, ACTIVO
FROM producto
;
--------------------------------------------------------
--  DDL for View VISTAROLES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAROLES" ("ID_ROL", "NOMBRE", "ID_USUARIO") AS 
  SELECT ID_ROL, NOMBRE, ID_USUARIO
FROM rol
;
--------------------------------------------------------
--  DDL for View VISTASUCURSALES
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTASUCURSALES" ("ID_SUCURSAL", "NOMBRE", "UBICACION", "TELEFONO") AS 
  SELECT ID_SUCURSAL, NOMBRE, UBICACION, TELEFONO
FROM sucursal
;
--------------------------------------------------------
--  DDL for View VISTAUSUARIOS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAUSUARIOS" ("ID_USUARIO", "USERNAME", "PASSWORD", "NOMBRE", "APELLIDO", "CORREO", "TELEFONO", "ACTIVO") AS 
  SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO, ACTIVO
FROM usuario
;
--------------------------------------------------------
--  DDL for View VISTAVENTAS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAVENTAS" ("ID_VENTA", "SUBTOTAL", "IVA", "TOTAL", "ID_CLIENTE", "ID_PRODUCTO") AS 
  SELECT ID_VENTA, SUBTOTAL, IVA, TOTAL, ID_CLIENTE, ID_PRODUCTO
FROM venta
;
REM INSERTING into DBADMIN.ACCESORIO
SET DEFINE OFF;
Insert into DBADMIN.ACCESORIO (ID_ACCESORIO,NOMBRE,DESCRIPCION,PRECIO,STOCK,ID_CATEGORIA) values ('2','RepuestoD PrestoBarba','Para afeitar','3250','0','2');
REM INSERTING into DBADMIN.CATEGORIA
SET DEFINE OFF;
Insert into DBADMIN.CATEGORIA (ID_CATEGORIA,NOMBRE,ACTIVO,DESCRIPCION) values ('2','Electrodomésticos','1','Toda máquina de uso doméstico');
Insert into DBADMIN.CATEGORIA (ID_CATEGORIA,NOMBRE,ACTIVO,DESCRIPCION) values ('3','Alimentos','1','Todo lo comestible');
REM INSERTING into DBADMIN.CLIENTE
SET DEFINE OFF;
Insert into DBADMIN.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TELEFONO,CORREO,DIRECCION,ACTIVO) values ('2','Josue','Campos Acuna','6323-2495','coder.josue@gmail.com',null,'1');
Insert into DBADMIN.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TELEFONO,CORREO,DIRECCION,ACTIVO) values ('3','Emmanuel','Campos Acuna','8362-5756','coder.josue@gmail.com',null,'1');
REM INSERTING into DBADMIN.DETALLE_PEDIDO
SET DEFINE OFF;
REM INSERTING into DBADMIN.DEVOLUCION
SET DEFINE OFF;
REM INSERTING into DBADMIN.EMPLEADO
SET DEFINE OFF;
REM INSERTING into DBADMIN.PEDIDO
SET DEFINE OFF;
REM INSERTING into DBADMIN.PRODUCTO
SET DEFINE OFF;
REM INSERTING into DBADMIN.ROL
SET DEFINE OFF;
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('1','Usuario');
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('2','Empleado');
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('3','Administrador');
REM INSERTING into DBADMIN.SUCURSAL
SET DEFINE OFF;
Insert into DBADMIN.SUCURSAL (ID_SUCURSAL,NOMBRE,UBICACION,TELEFONO) values ('2','Punto Rojo','Alajuela','2483-9898');
REM INSERTING into DBADMIN.USUARIO
SET DEFINE OFF;
Insert into DBADMIN.USUARIO (USERNAME,PASSWORD,NOMBRE,APELLIDO,CORREO,TELEFONO,ACTIVO,ID_USUARIO,ID_ROL) values ('Camacu0301','Camacu0303','Josue','Campos Acuna','coder.josue@gmail.com','6323-2495','1','2','1');
Insert into DBADMIN.USUARIO (USERNAME,PASSWORD,NOMBRE,APELLIDO,CORREO,TELEFONO,ACTIVO,ID_USUARIO,ID_ROL) values ('Admin','Password','Admin','No aplica','a@gmail.com','8888-8888','1','3','3');
REM INSERTING into DBADMIN.VENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."PK_CATEGORIA" ON "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SUCURSAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."PK_SUCURSAL" ON "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure CONSULTARACCESORIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARACCESORIOS" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR SELECT
                             a.nombre,
                             a.descripcion,
                             a.precio,
                             a.stock,
                             c.nombre AS nombre_categoria
                         FROM
                                  accesorio a
                             JOIN categoria c ON a.id_categoria = c.id_categoria;

END consultaraccesorios;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARCATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARCATEGORIA" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR SELECT
                             nombre,
                             activo,
                             descripcion
                         FROM
                                 categoria;

END consultarCategoria;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARDETALLEPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARDETALLEPEDIDO" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        d.Id_detalle,
        d.Id_pedido,
        p.descripcion AS nombre_producto,
        d.cantidad,
        d.precio,
        d.total
    FROM
        Detalle_pedido d
    JOIN
        producto p ON d.Id_producto = p.id_producto;
END consultarDetallePedido;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARDEVOLUCIONES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARDEVOLUCIONES" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        d.Id_devolucion,
        d.Id_cliente,
        d.fecha_devolucion,
        d.cantidad,
        d.Motivo
    FROM
        devolucion d
    JOIN
        cliente c ON d.Id_devolucion = c.id_cliente;
END consultarDevoluciones;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARPEDIDOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARPEDIDOS" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        Id_pedido,
        Id_cliente,
        fecha_pedido,
        estado
    FROM
        pedido;
END consultarPedidos;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARPRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARPRODUCTOS" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        Id_producto,
        Descripcion,
        Precio,
        Stock,
        Id_categoria,
        Id_sucursal,
        activo
    FROM
        producto;
END consultarProductos;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARROL" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        Id_rol,
        Nombre,
        Id_usuario
    FROM
        rol;
END consultarRol;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARSUCURSAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARSUCURSAL" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        Id_sucursal,
        Nombre,
        ubicacion,
        telefono
    FROM
        sucursal;
END consultarSucursal;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARUSUARIOPORUSERNAME
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARUSUARIOPORUSERNAME" (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2,
    p_resultado OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        username,
        password,
        nombre,
        apellido,
        correo,
        telefono,
        activo,
        id_rol,
        id_usuario
    FROM
        usuario
    WHERE
        Username = p_username and password=p_password;
END;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARUSUARIOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARUSUARIOS" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR SELECT
                             Username,
                             nombre,
                             apellido,
                             activo
                         FROM
                             usuario;

END;

/
--------------------------------------------------------
--  DDL for Procedure CONSULTARVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."CONSULTARVENTA" (
    p_resultado OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_resultado FOR
    SELECT
        Id_venta,
        subtotal,
        iva,
        total,
        id_cliente,
        id_producto
    FROM
        venta;
END consultarVenta;

/
--------------------------------------------------------
--  DDL for Procedure DESACTIVARUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."DESACTIVARUSUARIO" (
    p_id_usuario   IN usuario.id_usuario%TYPE
) AS
BEGIN
    UPDATE usuario
    SET 
        activo = 0   -- Set activo column to 0 (deactivate user)
    WHERE id_usuario = p_id_usuario;

    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Usuario no encontrado.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error al desactivar usuario: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARACCESORIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARACCESORIO" (
    p_id_accesorio IN NUMBER
) AS
BEGIN
    DELETE FROM accesorio
    WHERE id_accesorio = p_id_accesorio;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARCATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARCATEGORIA" (
    p_id_categoria IN NUMBER
) AS
BEGIN
    DELETE FROM categoria
    WHERE id_categoria = p_id_categoria;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARDETALLEPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARDETALLEPEDIDO" (
    p_id_detalle IN NUMBER
) AS
BEGIN
    DELETE FROM detalle_pedido
    WHERE id_detalle = p_id_detalle;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARDEVOLUCIONES
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARDEVOLUCIONES" (
    p_id_devolucion IN NUMBER
) AS
BEGIN
    DELETE FROM devolucion
    WHERE id_devolucion = p_id_devolucion;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARPEDIDOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARPEDIDOS" (
    p_id_pedido IN NUMBER
) AS
BEGIN
    DELETE FROM pedido
    WHERE id_pedido = p_id_pedido;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARPRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARPRODUCTO" (
    p_id_producto IN NUMBER
) AS
BEGIN
    DELETE FROM producto
    WHERE id_producto = p_id_producto;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARROL" (
    p_id_rol IN NUMBER
) AS
BEGIN
    DELETE FROM rol
    WHERE id_rol = p_id_rol;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARSUCURSAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARSUCURSAL" (
    p_id_sucursal IN NUMBER
) AS
BEGIN
    DELETE FROM sucursal
    WHERE id_sucursal = p_id_sucursal;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARUSUARIO" (
    p_id_usuario IN NUMBER
) AS
BEGIN
    DELETE FROM usuario
    WHERE id_usuario = p_id_usuario;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINARVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."ELIMINARVENTA" (
    p_id_venta IN NUMBER
) AS
BEGIN
    DELETE FROM venta
    WHERE id_venta = p_id_venta;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARACCESORIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARACCESORIO" (
    p_id_accesorio   IN NUMBER,
    p_nombre         IN VARCHAR2,
    p_descripcion    IN VARCHAR2,
    p_precio         IN NUMBER,
    p_stock          IN NUMBER,
    p_id_categoria   IN NUMBER
) AS
BEGIN
    UPDATE accesorio
    SET 
        nombre = p_nombre,
        descripcion = p_descripcion,
        precio = p_precio,
        stock = p_stock,
        id_categoria = p_id_categoria
    WHERE id_accesorio = p_id_accesorio;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARCATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARCATEGORIA" (
    p_id_categoria   IN NUMBER,
    p_nombre IN VARCHAR2,
    p_activo IN NUMBER,
    p_descripcion    IN VARCHAR2
) AS
BEGIN
    UPDATE categoria
    SET 
        nombre = p_nombre,
        activo = p_activo,
        descripcion = p_descripcion
    WHERE id_categoria = p_id_categoria;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARDETALLEPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARDETALLEPEDIDO" (
    p_id_detalle   IN NUMBER,
    p_cantidad IN VARCHAR2,
    p_precio IN NUMBER,
    p_total   IN VARCHAR2
) AS
BEGIN
    UPDATE detalle_pedido
    SET 
        cantidad = p_cantidad,
        precio = p_precio,
        total = p_total
    WHERE id_detalle = p_id_detalle;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARDEVOLUCION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARDEVOLUCION" (
    p_id_devolucion   IN NUMBER,
    p_fecha_devolucion IN DATE,
    p_cantidad IN NUMBER,
    p_motivo   IN VARCHAR2
) AS
BEGIN
    UPDATE detalle_pedido
    SET 
        cantidad = p_cantidad,
        precio = p_precio,
        total = p_total
    WHERE id_detalle = p_id_detalle;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARPEDIDO" (
    p_id_pedido   IN NUMBER,
    p_fecha_pedido IN DATE,
    p_estado IN NUMBER
) AS
BEGIN
    UPDATE pedido
    SET  
        fecha_pedido = SYSDATE,
        estado = p_estado
    WHERE id_pedido = p_id_pedido;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARPRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARPRODUCTO" (
    p_id_producto NUMBER,
    p_descripcion VARCHAR2,
    p_precio NUMBER,
    p_stock NUMBER,
    p_id_categoria NUMBER,
    p_id_sucursal NUMBER,
    p_activo NUMBER
) AS
BEGIN
    UPDATE producto
    SET  
        descripcion = p_descripcion, 
        precio = p_precio ,
        stock = p_stock ,
        activo = p_activo 
        WHERE id_producto = p_id_producto;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARROL" (
    p_id_rol NUMBER,
    p_nombre VARCHAR2,
    p_id_usuario NUMBER
) AS
BEGIN
    UPDATE rol
    SET 
        nombre = p_nombre,
        id_usuario=p_id_usuario
        WHERE id_rol = p_id_rol;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARSUCURSAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARSUCURSAL" (
    p_id_sucursal NUMBER,
    p_nombre VARCHAR2,
    p_ubicacion VARCHAR2,
    p_telefono VARCHAR2
) AS
BEGIN
    UPDATE sucursal
    SET 
        nombre = p_nombre,
        ubicacion = p_ubicacion,
        telefono = p_telefono
        WHERE id_sucursal = p_id_sucursal;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARUSUARIO" (
    p_id_usuario   IN usuario.id_usuario%TYPE,
    p_username     IN usuario.username%TYPE,
    p_nombre       IN usuario.nombre%TYPE,
    p_apellido     IN usuario.apellido%TYPE,
    p_correo       IN usuario.correo%TYPE,
    p_telefono     IN usuario.telefono%TYPE
) AS
BEGIN
    UPDATE usuario
    SET 
        username = p_username,
        nombre = p_nombre,
        apellido = p_apellido,
        correo = p_correo,
        telefono = p_telefono
    WHERE id_usuario = p_id_usuario;

    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Usuario no encontrado.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20002, 'Error al modificar usuario: ' || SQLERRM);
END;

/
--------------------------------------------------------
--  DDL for Procedure MODIFICARVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."MODIFICARVENTA" (
    p_id_venta NUMBER,
    p_subtotal NUMBER,
    p_iva NUMBER,
    p_total NUMBER
) AS
    v_calcula_total NUMBER;
BEGIN

    v_calcula_total := p_subtotal + (p_subtotal * p_iva);


    UPDATE venta
    SET 
        subtotal = p_subtotal,
        iva = p_iva,
        total = v_calcula_total
    WHERE id_venta = p_id_venta;

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARACCESORIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARACCESORIO" (
    p_nombre       IN VARCHAR2,
    p_descripcion  IN VARCHAR2,
    p_precio       IN NUMBER,
    p_stock        IN NUMBER,
    p_id_categoria IN NUMBER
) AS
BEGIN
    INSERT INTO accesorio (
        nombre,
        descripcion,
        precio,
        stock,
        id_categoria
    ) VALUES (
        p_nombre,
        p_descripcion,
        p_precio,
        p_stock,
        p_id_categoria
    );

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARCATEGORIA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARCATEGORIA" (
    p_nombre       IN VARCHAR2,
    p_activo IN NUMBER,
    p_descripcion IN VARCHAR2
) AS
BEGIN
    INSERT INTO categoria (
        nombre,
        activo,
        descripcion
    ) VALUES (
        p_nombre,
        p_activo,
        p_descripcion
    );

    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARDETALLEPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARDETALLEPEDIDO" (
    p_id_pedido IN NUMBER,
    p_id_producto IN NUMBER,
    p_cantidad IN NUMBER,
    p_precio IN NUMBER
) AS
    v_pedido_exist NUMBER;
    v_producto_exist NUMBER;
    v_total NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO v_pedido_exist
    FROM pedido
    WHERE id_pedido = p_id_pedido;

    SELECT COUNT(*)
    INTO v_producto_exist
    FROM producto
    WHERE id_producto = p_id_producto;

    IF v_pedido_exist = 1 AND v_producto_exist = 1 THEN
        v_total := p_cantidad * p_precio;

        INSERT INTO detalle_pedido (
            Id_pedido,
            Id_producto,
            cantidad,
            precio,
            total
        ) VALUES (
            p_id_pedido,
            p_id_producto,
            p_cantidad,
            p_precio,
            v_total
        );

        COMMIT;
    ELSE
        DBMS_OUTPUT.PUT_LINE('Error: El id_pedido o id_producto no existe.');
    END IF;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARDEVOLUCION
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARDEVOLUCION" (
    p_id_cliente IN NUMBER,
    p_id_producto IN NUMBER,
    p_cantidad IN NUMBER,
    p_motivo IN VARCHAR2
) AS
    v_id_devolucion NUMBER;
    v_producto_exist NUMBER;
    v_cliente_exist NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO v_producto_exist
    FROM producto
    WHERE id_producto = p_id_producto;

    SELECT COUNT(*)
    INTO v_cliente_exist
    FROM cliente
    WHERE id_cliente = p_id_cliente;


    IF v_producto_exist = 1 AND v_cliente_exist = 1 THEN

        SELECT seq_devolucion.NEXTVAL INTO v_id_devolucion FROM dual;


        INSERT INTO devolucion (
            ID_DEVOLUCION,
            ID_CLIENTE,
            ID_PRODUCTO,
            FECHA_DEVOLUCION,
            CANTIDAD,
            MOTIVO
        ) VALUES (
            v_id_devolucion,
            p_id_cliente,
            p_id_producto,
            SYSDATE, 
            p_cantidad,
            p_motivo
        );

        COMMIT; 
        DBMS_OUTPUT.PUT_LINE('Devolución registrada correctamente. ID_DEVOLUCION = ' || v_id_devolucion);
    ELSE
        DBMS_OUTPUT.PUT_LINE('Error: El ID_PRODUCTO o ID_CLIENTE no existe.');
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar devolución: ' || SQLERRM);
        ROLLBACK; 
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARPEDIDO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARPEDIDO" (
    p_id_cliente IN NUMBER,
    p_fecha_pedido IN DATE,
    p_estado IN NUMBER
) AS
    v_cliente_exist NUMBER;
    v_id_pedido NUMBER;
BEGIN

    SELECT COUNT(*)
    INTO v_cliente_exist
    FROM cliente
    WHERE id_cliente = p_id_cliente;

    IF v_cliente_exist > 0 THEN

        SELECT secuencia_pedido.NEXTVAL INTO v_id_pedido FROM dual;


        INSERT INTO pedido (
            Id_pedido,
            Id_cliente,
            fecha_pedido,
            estado
        ) VALUES (
            v_id_pedido,
            p_id_cliente,
            SYSDATE,
            p_estado
        );

        COMMIT; 
        DBMS_OUTPUT.PUT_LINE('Pedido registrado correctamente. ID_pedido: ' || v_id_pedido);
    ELSE
        DBMS_OUTPUT.PUT_LINE('El cliente no existe. No se puede registrar el pedido.');
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar el pedido: ' || SQLERRM);
        ROLLBACK; 
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARPRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARPRODUCTO" (
    p_descripcion VARCHAR2,
    p_precio NUMBER,
    p_stock NUMBER,
    p_id_categoria NUMBER,
    p_id_sucursal NUMBER,
    p_activo NUMBER
)
IS
    v_categoria_exist NUMBER;
    v_sucursal_exist NUMBER;
BEGIN

    SELECT COUNT(*) INTO v_categoria_exist
    FROM categoria
    WHERE id_categoria = p_id_categoria;


    SELECT COUNT(*) INTO v_sucursal_exist
    FROM sucursal
    WHERE id_sucursal = p_id_sucursal;


    IF v_categoria_exist = 1 AND v_sucursal_exist = 1 THEN
        INSERT INTO producto (descripcion, precio, stock, id_categoria, id_sucursal, activo)
        VALUES (p_descripcion, p_precio, p_stock, p_id_categoria, p_id_sucursal, p_activo);
        COMMIT; 
        DBMS_OUTPUT.PUT_LINE('Producto registrado correctamente.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Error: La categoría o la sucursal especificada no existe.');
    END IF;
END registrarProducto;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARROL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARROL" (
    p_id_rol IN NUMBER DEFAULT NULL,
    p_nombre IN VARCHAR2
)
IS
BEGIN
    INSERT INTO rol (id_rol, nombre)
    VALUES (p_id_rol, p_nombre);
    COMMIT;
END registrarRol;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARSUCURSAL
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARSUCURSAL" (
    p_nombre IN VARCHAR2,
    p_ubicacion IN VARCHAR2,
    p_telefono IN VARCHAR2
)
IS
    v_id_sucursal NUMBER;
BEGIN
    -- Obtener el próximo valor de la secuencia
    SELECT seq_id_sucursal.NEXTVAL INTO v_id_sucursal FROM dual;

    -- Insertar los datos en la tabla
    INSERT INTO sucursal (ID_SUCURSAL, NOMBRE, UBICACION, TELEFONO)
    VALUES (v_id_sucursal, p_nombre, p_ubicacion, p_telefono);

    -- Confirmar la transacción
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        -- Manejar cualquier error
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Error al registrar la sucursal: ' || SQLERRM);
END registrarSucursal;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARUSUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARUSUARIO" (
    p_username IN VARCHAR2,
    p_password IN VARCHAR2,
    p_nombre   IN VARCHAR2,
    p_apellido IN VARCHAR2,
    p_correo   IN VARCHAR2,
    p_telefono IN VARCHAR2,
    p_id_rol   IN NUMBER  -- New parameter for ID_ROL
) AS
    v_id_cliente NUMBER;
BEGIN
    INSERT INTO usuario (
        username,
        password,
        nombre,
        apellido,
        correo,
        telefono,
        activo,
        id_rol  -- Insert ID_ROL into usuario table
    ) VALUES (
        p_username,
        p_password,
        p_nombre,
        p_apellido,
        p_correo,
        p_telefono,
        1,
        p_id_rol
    );

    -- Assuming you also need to insert into cliente (adjust if necessary)
    INSERT INTO cliente (
        username,
        nombre,
        password,
        apellido,
        correo,
        telefono,
        activo
    ) VALUES (
        p_username,
        p_nombre,
        p_password,
        p_apellido,
        p_correo,
        p_telefono,
        1
    );
    COMMIT;
END;

/
--------------------------------------------------------
--  DDL for Procedure REGISTRARVENTA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DBADMIN"."REGISTRARVENTA" (
    p_id_venta IN NUMBER,
    p_subtotal IN NUMBER,
    p_iva IN NUMBER,
    p_id_cliente IN NUMBER,
    p_id_producto IN NUMBER
)
IS
    v_cliente_exist NUMBER;
    v_producto_exist NUMBER;
    v_total NUMBER;
BEGIN

    v_total := p_subtotal + (p_subtotal * p_iva);

    SELECT COUNT(*)
    INTO v_cliente_exist
    FROM cliente
    WHERE id_cliente = p_id_cliente;


    SELECT COUNT(*)
    INTO v_producto_exist
    FROM producto
    WHERE id_producto = p_id_producto;


    IF v_cliente_exist = 1 AND v_producto_exist = 1 THEN
        INSERT INTO venta (id_venta, subtotal, iva, total, id_cliente, id_producto)
        VALUES (p_id_venta, p_subtotal, p_iva, v_total, p_id_cliente, p_id_producto);
        COMMIT;

        DBMS_OUTPUT.PUT_LINE('Venta registrada correctamente.');
    ELSE

        DBMS_OUTPUT.PUT_LINE('Error: El cliente o el producto no existen.');
    END IF;

EXCEPTION
    WHEN OTHERS THEN

        DBMS_OUTPUT.PUT_LINE('Error: Ha ocurrido un error al intentar registrar la venta.');
END registrarVenta;

/
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."EMPLEADO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."EMPLEADO" ADD PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCESORIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ACCESORIO" MODIFY ("ID_ACCESORIO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."ACCESORIO" ADD PRIMARY KEY ("ID_ACCESORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVOLUCION
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DEVOLUCION" MODIFY ("ID_DEVOLUCION" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD PRIMARY KEY ("ID_DEVOLUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."VENTA" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."SUCURSAL" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."SUCURSAL" ADD CONSTRAINT "PK_SUCURSAL" PRIMARY KEY ("ID_SUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."PRODUCTO" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."ROL" ADD PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PEDIDO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."PEDIDO" ADD PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."CATEGORIA" ADD CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" MODIFY ("ID_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCESORIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ACCESORIO" ADD CONSTRAINT "FK_CATEGORIA_ACCESORIO" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "DBADMIN"."PEDIDO" ("ID_PEDIDO") ENABLE;
  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEVOLUCION
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."EMPLEADO" ADD CONSTRAINT "FK_EMPLEADO_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "DBADMIN"."USUARIO" ("ID_USUARIO") ENABLE;
  ALTER TABLE "DBADMIN"."EMPLEADO" ADD FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PEDIDO" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PRODUCTO" ADD FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "DBADMIN"."PRODUCTO" ADD FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "DBADMIN"."ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."VENTA" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "DBADMIN"."VENTA" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
