--------------------------------------------------------
-- Archivo creado  - jueves-julio-18-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCESORIO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."ACCESORIO" 
   (	"ID_ACCESORIO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER, 
	"ID_CATEGORIA" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"DESCRIPCION" VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"DIRECCION" VARCHAR2(500 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(512 BYTE), 
	"ACTIVO" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table DETALLE_PEDIDO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."DETALLE_PEDIDO" 
   (	"ID_DETALLE" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_PEDIDO" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIO" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2)
   ) ;
--------------------------------------------------------
--  DDL for Table DEVOLUCION
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."DEVOLUCION" 
   (	"ID_DEVOLUCION" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER, 
	"FECHA_DEVOLUCION" DATE, 
	"CANTIDAD" NUMBER, 
	"MOTIVO" VARCHAR2(500 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERNAME" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(512 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"CORREO" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"ID_SUCURSAL" NUMBER, 
	"ACTIVO" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table PEDIDO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."PEDIDO" 
   (	"ID_PEDIDO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CLIENTE" NUMBER, 
	"FECHA_PEDIDO" TIMESTAMP (6), 
	"ESTADO" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"PRECIO" NUMBER(10,2), 
	"STOCK" NUMBER, 
	"RUTA_IMAGEN" VARCHAR2(1024 BYTE), 
	"ID_CATEGORIA" NUMBER, 
	"ID_SUCURSAL" NUMBER, 
	"ACTIVO" NUMBER(1,0)
   ) ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."ROL" 
   (	"ID_ROL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."SUCURSAL" 
   (	"ID_SUCURSAL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"UBICACION" VARCHAR2(200 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."USUARIO" 
   (	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(512 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"CORREO" VARCHAR2(25 BYTE), 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"ACTIVO" NUMBER(1,0), 
	"ID_USUARIO" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_ROL" NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "DBADMIN"."VENTA" 
   (	"ID_VENTA" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBTOTAL" NUMBER(10,2), 
	"IVA" NUMBER(10,2), 
	"TOTAL" NUMBER(10,2), 
	"ID_CLIENTE" NUMBER, 
	"ID_PRODUCTO" NUMBER
   ) ;
REM INSERTING into DBADMIN.ACCESORIO
SET DEFINE OFF;
REM INSERTING into DBADMIN.CATEGORIA
SET DEFINE OFF;
REM INSERTING into DBADMIN.CLIENTE
SET DEFINE OFF;
Insert into DBADMIN.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TELEFONO,CORREO,DIRECCION,USERNAME,PASSWORD,ACTIVO) values ('2','Josue','Campos Acuna','6323-2495','coder.josue@gmail.com',null,'Camacu0301','Camacu0303','1');
Insert into DBADMIN.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,TELEFONO,CORREO,DIRECCION,USERNAME,PASSWORD,ACTIVO) values ('3','Emmanuel','Campos Acuna','8362-5756','coder.josue@gmail.com',null,'Eca0490','Password','1');
REM INSERTING into DBADMIN.DETALLE_PEDIDO
SET DEFINE OFF;
REM INSERTING into DBADMIN.DEVOLUCION
SET DEFINE OFF;
REM INSERTING into DBADMIN.EMPLEADO
SET DEFINE OFF;
REM INSERTING into DBADMIN.PEDIDO
SET DEFINE OFF;
REM INSERTING into DBADMIN.PRODUCTO
SET DEFINE OFF;
REM INSERTING into DBADMIN.ROL
SET DEFINE OFF;
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('1','Usuario');
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('2','Empleado');
Insert into DBADMIN.ROL (ID_ROL,NOMBRE) values ('3','Administrador');
REM INSERTING into DBADMIN.SUCURSAL
SET DEFINE OFF;
REM INSERTING into DBADMIN.USUARIO
SET DEFINE OFF;
Insert into DBADMIN.USUARIO (USERNAME,PASSWORD,NOMBRE,APELLIDO,CORREO,TELEFONO,ACTIVO,ID_USUARIO,ID_ROL) values ('Camacu0301','Camacu0303','Josue','Campos Acuna','coder.josue@gmail.com','6323-2495','1','2','1');
REM INSERTING into DBADMIN.VENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007626
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007626" ON "DBADMIN"."ACCESORIO" ("ID_ACCESORIO") 
  ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."PK_CATEGORIA" ON "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007634
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007634" ON "DBADMIN"."CLIENTE" ("ID_CLIENTE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007643
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007643" ON "DBADMIN"."DETALLE_PEDIDO" ("ID_DETALLE") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007655
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007655" ON "DBADMIN"."DEVOLUCION" ("ID_DEVOLUCION") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007631
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007631" ON "DBADMIN"."EMPLEADO" ("ID_EMPLEADO") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007640
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007640" ON "DBADMIN"."PEDIDO" ("ID_PEDIDO") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007622
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007622" ON "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007659
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007659" ON "DBADMIN"."ROL" ("ID_ROL") 
  ;
--------------------------------------------------------
--  DDL for Index PK_SUCURSAL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."PK_SUCURSAL" ON "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007653
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007653" ON "DBADMIN"."USUARIO" ("ID_USUARIO") 
  ;
--------------------------------------------------------
--  DDL for Index SYS_C007636
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBADMIN"."SYS_C007636" ON "DBADMIN"."VENTA" ("ID_VENTA") 
  ;
--------------------------------------------------------
--  Constraints for Table ACCESORIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ACCESORIO" MODIFY ("ID_ACCESORIO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."ACCESORIO" ADD PRIMARY KEY ("ID_ACCESORIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."CATEGORIA" ADD CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" MODIFY ("ID_DETALLE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD PRIMARY KEY ("ID_DETALLE")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVOLUCION
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DEVOLUCION" MODIFY ("ID_DEVOLUCION" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD PRIMARY KEY ("ID_DEVOLUCION")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."EMPLEADO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."EMPLEADO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."EMPLEADO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."EMPLEADO" ADD PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PEDIDO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."PEDIDO" ADD PRIMARY KEY ("ID_PEDIDO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."PRODUCTO" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."ROL" ADD PRIMARY KEY ("ID_ROL")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUCURSAL
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."SUCURSAL" MODIFY ("ID_SUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."SUCURSAL" ADD CONSTRAINT "PK_SUCURSAL" PRIMARY KEY ("ID_SUCURSAL")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."USUARIO" ADD PRIMARY KEY ("ID_USUARIO")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."VENTA" MODIFY ("ID_VENTA" NOT NULL ENABLE);
  ALTER TABLE "DBADMIN"."VENTA" ADD PRIMARY KEY ("ID_VENTA")
  USING INDEX  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCESORIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."ACCESORIO" ADD CONSTRAINT "FK_CATEGORIA_ACCESORIO" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "DBADMIN"."PEDIDO" ("ID_PEDIDO") ENABLE;
  ALTER TABLE "DBADMIN"."DETALLE_PEDIDO" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEVOLUCION
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "DBADMIN"."DEVOLUCION" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."EMPLEADO" ADD FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PEDIDO" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."PRODUCTO" ADD FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DBADMIN"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "DBADMIN"."PRODUCTO" ADD FOREIGN KEY ("ID_SUCURSAL")
	  REFERENCES "DBADMIN"."SUCURSAL" ("ID_SUCURSAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."USUARIO" ADD CONSTRAINT "FK_USUARIO_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "DBADMIN"."ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "DBADMIN"."VENTA" ADD FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "DBADMIN"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "DBADMIN"."VENTA" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "DBADMIN"."CLIENTE" ("ID_CLIENTE") ENABLE;
