CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAACCESORIOS" ("ID_ACCESORIO", "NOMBRE", "DESCRIPCION", "PRECIO", "STOCK", "ID_CATEGORIA") AS SELECT ID_ACCESORIO, NOMBRE, DESCRIPCION, PRECIO, STOCK, ID_CATEGORIA
FROM Accesorio;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTACATEGORIAS" ("ID_CATEGORIA", "NOMBRE", "ACTIVO", "DESCRIPCION") AS SELECT ID_CATEGORIA, NOMBRE, ACTIVO, DESCRIPCION
FROM categoria;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTACLIENTES" ("ID_CLIENTE", "NOMBRE", "APELLIDO", "TELEFONO", "CORREO", "DIRECCION", "USERNAME", "PASSWORD", "ACTIVO") AS SELECT ID_CLIENTE, NOMBRE, APELLIDO, TELEFONO, CORREO, DIRECCION, USERNAME, PASSWORD, ACTIVO
FROM cliente;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTADETALLESDEDIDO" ("ID_DETALLE", "ID_PEDIDO", "ID_PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL") AS SELECT ID_DETALLE, ID_PEDIDO, ID_PRODUCTO, CANTIDAD, PRECIO, TOTAL
FROM detalle_pedido;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTADEVOLUCIONES" ("ID_DEVOLUCION", "ID_CLIENTE", "ID_PRODUCTO", "FECHA_DEVOLUCION", "CANTIDAD", "MOTIVO") AS SELECT ID_DEVOLUCION, ID_CLIENTE, ID_PRODUCTO, FECHA_DEVOLUCION, CANTIDAD, MOTIVO
FROM devolucion;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAEMPLEADOS" ("ID_EMPLEADO", "USERNAME", "NOMBRE", "PASSWORD", "APELLIDO", "CORREO", "TELEFONO", "ID_SUCURSAL", "ACTIVO") AS SELECT ID_EMPLEADO, USERNAME, NOMBRE, PASSWORD, APELLIDO, CORREO, TELEFONO, ID_SUCURSAL, ACTIVO
FROM empleado;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAPEDIDOS" ("ID_PEDIDO", "ID_CLIENTE", "FECHA_PEDIDO", "ESTADO") AS SELECT ID_PEDIDO, ID_CLIENTE, FECHA_PEDIDO, ESTADO
FROM pedido;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAPRODUCTOS" ("ID_PRODUCTO", "DESCRIPCION", "PRECIO", "STOCK", "ID_CATEGORIA", "ID_SUCURSAL", "ACTIVO") AS SELECT ID_PRODUCTO, DESCRIPCION, PRECIO, STOCK, ID_CATEGORIA, ID_SUCURSAL, ACTIVO
FROM producto;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAROLES" ("ID_ROL", "NOMBRE", "ID_USUARIO") AS SELECT ID_ROL, NOMBRE, ID_USUARIO
FROM rol;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTASUCURSALES" ("ID_SUCURSAL", "NOMBRE", "UBICACION", "TELEFONO") AS SELECT ID_SUCURSAL, NOMBRE, UBICACION, TELEFONO
FROM sucursal;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAUSUARIOS" ("ID_USUARIO", "USERNAME", "PASSWORD", "NOMBRE", "APELLIDO", "CORREO", "TELEFONO", "ACTIVO") AS SELECT ID_USUARIO, USERNAME, PASSWORD, NOMBRE, APELLIDO, CORREO, TELEFONO, ACTIVO
FROM usuario;

CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "DBADMIN"."VISTAVENTAS" ("ID_VENTA", "SUBTOTAL", "IVA", "TOTAL", "ID_CLIENTE", "ID_PRODUCTO") AS SELECT ID_VENTA, SUBTOTAL, IVA, TOTAL, ID_CLIENTE, ID_PRODUCTO
FROM venta;
